### ISSUE TITLE
programmatically show popups for given features

### ISSUE THREAD

**Issue by ivanmobigis** [nickcam/PopupExtended#1]
Hi there.. great module !

I'm coming from the leaflet/openlayers world and am searching for a way to have multiple (small) popups associated with features, as a way of implementing 'smart' labels for point features.

Your module is almost perfect, except that I can't work out how to programmatically open popups associated with individual features.. (i.e. not wait for the user to click on them). is/could this be possible ?

cheers !!

-i

**Comment by ivanmobigis** [comment]
ok so to respond to myself, this is pretty simple:

```
require(["esri/dijit/PopupTemplate", "PopupExtended.js"], function(PopupTemplate, PopupExtended) {

    var popupTemplate = new PopupTemplate({
        extended: {
            actions: []
        }
    });
    popupTemplate.setContent("this is my popup");
    marker.setInfoTemplate(popupTemplate);


    var extendedPopup = new PopupExtended({
        extended: {
            themeClass: "light",
            draggable: false,
            defaultWidth: 50,
            actions: null,
            hideOnOffClick: false,
            multiple: true
        }
    }, dojo.create("div"));
    extendedPopup.setMap(map); 

    extendedPopup.setFeatures([marker])
    extendedPopup.show(center); // center is an esri point geometry

});
```

where 'marker' is a marker(/graphic) as i loop over all the markers in a feature layer.

thanks !

-i

**Comment by nickcam** [comment]
Hi ivanmobigis,

Good stuff that you worked it out! I had some commented out code at the bottom of index.html that programatically opens a couple of popups. It's in testApiMethods().

Seems you've got it sorted anyway. Just as an extra you could set the content using the template fields of a PopupTemplate. Check out the api docs of the PopupTemplate on the ESRI site. 

https://developers.arcgis.com/javascript/jsapi/popuptemplate-amd.html

Also if you don't want any extra actions just remove the actions property from the PopupTemplate.
One last thing. If you're only using small style popups, they will hide the content pane until maximized, so you'll have to set the title to see anything.

Hope it helps!

**Comment by ivanmobigis** [comment]
Hey nickcam, thanks for your reply. Your proposed method for programatically opening popups (in the example) is better than mine, because it provides a better way to clear them all off when needed.. it took me a little while to work out that the ExtendedPopup could/should be used as a singleton attached to the map, who manages his list of Popups.. a bit different to other apis. 

I combined this with a hack to pass mouse/touch events on the popup through to the underlying map to allow map nav when the user drags the popup to implement some nice looking labels.

cheers
