### ISSUE TITLE
3.17 broke some of this functionality

### ISSUE THREAD

**Issue by MarcBate** [nickcam/PopupExtended#4]
I'd like to use this with the latest version 3.24 of the ArcGIS JavaScript API. I did some trial and error and found that starting with 3.17, the popups don't appear when I uncomment your call to the testApiMethods function. Nothing happens when I click on the graphics layer graphics either. Any ideas?

When I actually incorporated your code into my solution built with 3.24, it worked as expected. I'm not sure why your index.html example doesn't work in 3.24.

**Comment by nickcam** [comment]
Hey man, so when you use the popup code in your own project or works ok? Is that right? If so then great...just do that! 

It's entirely possible the example could be broken in later releases. If you really need the example to run in the latest version I can take a look, if you could create a plunkr or some other demo that would be great though.

**Comment by MarcBate** [comment]
Yes, it is working for me with 3.25. There seems to be some issue with the themeClass: "extended" preventing the popups to be seen, but I'm not using that, so I'm good. Thanks.
