### ISSUE TITLE
With ArcGIS 4.x

### ISSUE THREAD

**Issue by dimpyvirk** [nickcam/PopupExtended#6]
I need to display multiple info windows (just like google maps does) for my graphics in Graphics using ArcGIS Javascript API 4.x. 
Is there a way I can use this or what changes do I need for it

**Comment by nickcam** [comment]
Hi mate, sorry this won't work in 4.x. A whole new component would need to be written to support 4.x.

**Comment by dimpyvirk** [comment]
Thanks Nick, any plans to write 4.x components

**Comment by nickcam** [comment]
No sorry. I haven't used this component in any projects myself for a few years and have no need for a 4.x version, so wasn't planning on building one.
