### ISSUE TITLE
PopupExtended with current version

### ISSUE THREAD

**Issue by stacklast** [nickcam/PopupExtended#8]
Hello!! Your work is amazing, I need your features over PopupExtended, do you know how to do the same with the [current ](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Popup.html)version of ArcGIS JS API ?

**Comment by nickcam** [comment]
H @stacklast - no sorry. This is a pretty old library, built it before v4 was even a thing. It would be a complete rewrite to update it to support v4.
